# Generated by Django 5.2.6 on 2025-10-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em: ')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50000)),
                ('cabecalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.noticia')),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tema'),
        ),
    ]
