# Generated by Django 5.2.6 on 2025-10-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
