# Generated by Django 5.2.6 on 2025-10-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_noticia_texto_delete_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(),
        ),
    ]
