# Generated by Django 5.2.6 on 2025-10-25 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_noticia_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em: ')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.noticia')),
            ],
        ),
    ]
