# Generated by Django 5.2.6 on 2025-10-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='noticia',
            new_name='coment_noticia',
        ),
    ]
