# Generated by Django 5.2.6 on 2025-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
