# Generated by Django 5.2.6 on 2025-11-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_noticia_visualizacoes'),
        ('portal', '0010_temas_iniciais'),
    ]

    operations = [
    ]
