# Generated by Django 5.2.6 on 2025-11-07 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_merge_0009_noticia_visualizacoes_0010_temas_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Lido em: ')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.noticia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
