# Generated by Django 5.2.6 on 2025-11-19 01:48

from django.db import migrations
import cloudinary.models

def fill_null_capa(apps, schema_editor):
    Noticia = apps.get_model('portal', 'Noticia')
    Noticia.objects.filter(capa__isnull=True).update(capa='')

class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0013_noticia_capa_alter_comentario_coment_noticia_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_null_capa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]