# Generated by Django 5.2.6 on 2025-11-19 01:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_noticia_capa_alter_comentario_coment_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
