# Generated by Django 5.2.6 on 2025-12-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_noticia_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios_noticias'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='legenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
