# Generated by Django 5.2.6 on 2025-12-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_noticia_capa'),
        ('portal', '0017_adicionar_mais_temas'),
    ]

    operations = [
    ]
