# Generated by Django 5.2.6 on 2025-12-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_noticia_audio_noticia_legenda_alter_noticia_capa'),
        ('portal', '0018_merge_20251203_1859'),
    ]

    operations = [
    ]
