# Generated by Django 5.2.6 on 2025-12-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20251206_1708'),
        ('portal', '0018_merge_20251203_1859'),
    ]

    operations = [
    ]
