# Generated by Django 5.2.6 on 2025-12-06 22:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_merge_20251206_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
