# Generated by Django 5.2.6 on 2025-12-08 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_noticia_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
