# Generated by Django 5.2.6 on 2025-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_noticia_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
